name: iplanit
version: 1.0.0+1

description: "A new Flutter project."

# Prevent the package from being accidentally published to pub.dev
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.1
  table_calendar: ^3.2.0
  shared_preferences: ^2.4.0
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
